apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: db
  namespace: vote
spec:
  clusterIP: 10.104.151.157
  clusterIPs:
  - 10.104.151.157
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
